version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install

  build:
    commands:
      - npm run build
      - ls -la
      - ls -la build

  post_build:
    commands:
      - echo "Deploying build folder to S3"
      - aws s3 sync build/ s3://basu.work-space.co.in --delete

artifacts:
  base-directory: build
  files:
    - '**/*'